Resolved parameter access problem in LocalDDP
mcrl/Megatron-LM-mcrl pull request #9
Opened 2024-02-10 16:16 UTC by ttochi

## Description

### Issue
- If exec `param.free()` in model initialization, an error occurs in the backward process that the grad tensor size does not match.
- This issue occurs when wrapping the model with LocalDDP(DistributedDataParallel) which is directly accessing `param.data` that has already been offloaded.

### Resolve
- Remove the part that directly accesses `param.data` inside LocalDDP(DistributedDataParallel).
- Parameter fetch/free around the code block that hooking the gradient accumulation function
    - To obtain the gradient accumulation function by execute `param.expand_as(param)` in below code block, parameter should be fetch to gpu.
https://github.com/mcrl/Megatron-LM-mcrl/blob/67807825aa133b64d42e96b873d4632313f2ccec/megatron/model/distributed.py#L171-L180

### Discussion
- If fetch/free of modules is unavoidable during LocalDDP initialization, it may be better to modify `training.py` instead of `megatron/model/distributed.py`

2024-02-11 05:38 UTC, gajagajago requested changes
Few miscellaneous changes requested!

2024-02-11 05:38 UTC, gajagajago commented on megatron/model/distributed.py
> +            # TODO (mcrl): check if spiral_tensor should be used instead of param.data
I think spiral_tensor is correct.

2024-02-11 05:38 UTC, gajagajago commented on megatron/model/distributed.py
For the above conditionals, please make on big conditional block for when `mpu.is_spiral_pipeline_parallel = True` and then set values according to parameter types (i.e., according to whether parameter is spiral_param or not). I think doing so improves readability and reduces future bug possibility.

2024-02-11 05:38 UTC, gajagajago commented on megatron/training.py
>                  model = [torchDDP(model_module, device_ids=[i], output_device=i,
I have never tested with torchDDP. Have you? Why is torchddp not supported for multi microbatch?
(If it is not crucial for us, we may for now prohibit using torch ddp with spiral by declaring so in the arguments.py check)

2024-02-12 06:34 UTC, ttochi commented on megatron/model/distributed.py
> +            # TODO (mcrl): check if spiral_tensor should be used instead of param.data
This part is changed since I changed the code to fetch parameter before initialize LocalDDP.

2024-02-12 06:34 UTC, ttochi commented on megatron/model/distributed.py
This part is changed since I changed the code to fetch parameter before initialize LocalDDP.

2024-02-12 06:36 UTC, ttochi commented on megatron/training.py
>                  model = [torchDDP(model_module, device_ids=[i], output_device=i,
I tested with torchDDP, but it is blocked by below code block.
https://github.com/mcrl/Megatron-LM-mcrl/blob/eaf017634f2b3118e724a28c07eabc6c7a15b26a/megatron/training.py#L503-L505

But I changed to fetch parameter before start initializing DDP module in modified code.

2024-02-12 06:38 UTC, ttochi commented
@gajagajago Please review new commit, Thanks! 😃

2024-02-12 07:34 UTC, gajagajago commented on megatron/training.py
> +        wrapped_model = []
I don't think we really need this `wrapped_model` list. All below things can be done in original model[]. Let's not add another unnecessary variable. I will approve the PR after this is changed!

2024-02-12 07:36 UTC, gajagajago commented on megatron/training.py
> +        wrapped_model = []
Please try with python list.map(lambda)! [ref](https://tykimos.github.io/2020/01/01/Python_Lambda_Map/) I think it will be better for readability

2024-02-13 03:07 UTC, ttochi commented on megatron/training.py
> +        wrapped_model = []
Reflect in new commit :)

2024-02-13 03:26 UTC, gajagajago approved these changes
Thanks! I will merge the PR.

2024-02-13 03:27 UTC, merged